
export const hard = [
    { key: '1', value: 'Mining' },
    { key: '2', value: 'Project Management' },
    { key: '3', value: 'Business Management' },
    { key: '4', value: 'Earth Science' },
    { key: '5', value: 'Manufacturing Operations' },
    { key: '6', value: 'Drilling Engineering' },
    { key: '7', value: 'Digital Literacy' },
    { key: '8', value: 'Maintenance & Repair' },
    { key: '9', value: 'Procurement' },
    { key: '10', value: 'Oil & Gas' },
    { key: '11', value: 'Utilities' },
    { key: '12', value: 'Construction Engineering' },
    { key: '13', value: 'Pharmaceutics' },
    { key: '14', value: 'Pharmaceutical Manufacturing' },
    { key: '15', value: 'Oncology' },
    { key: '16', value: 'Cardiology' },
    { key: '17', value: 'Biomedical Engineering' },
    { key: '18', value: 'Neurology' },
    { key: '19', value: 'Product Testing' },
    { key: '20', value: 'Product Development' },
    { key: '21', value: 'Family Medicine' },
    { key: '22', value: 'Product Marketing' },
    { key: '23', value: 'Food Manufacturing' },
    { key: '24', value: 'Food Service Operations' },
    { key: '25', value: 'Retail' },
    { key: '26', value: 'Air Force' },
    { key: '27', value: 'Airlines' },
    { key: '28', value: 'Aerospace Engineering' },
    { key: '29', value: 'Aircraft Management' },
    { key: '30', value: 'Composites' },
    { key: '31', value: 'Scientific Computing' },
    { key: '32', value: 'Automotive' },
    { key: '33', value: 'Customer Experience' },
    { key: '34', value: 'Chemical Processing' },
    { key: '35', value: 'Research' },
    { key: '36', value: 'Materials Science' },
    { key: '37', value: 'Architecture' },
    { key: '38', value: 'Machining' },
    { key: '39', value: 'Apparel' },
    { key: '40', value: 'Recruiting' },
    { key: '41', value: 'Inside Sales' },
    { key: '42', value: 'Forestry' },
    { key: '43', value: 'Printing' },
    { key: '44', value: 'Retail Packaging' },
    { key: '45', value: 'Graphic Design' },
    { key: '46', value: 'Advertising' },
    { key: '47', value: 'Electronics' },
    { key: '48', value: 'Robotics' },
    { key: '49', value: 'Software Testing' },
    { key: '50', value: 'Plastics' },
    { key: '51', value: 'Power Systems' },
    { key: '52', value: 'Environmental Science' },
    { key: '53', value: 'Environmental Consulting' },
    { key: '54', value: 'Entrepreneurship' },
    { key: '55', value: 'Instrumentation' },
    { key: '56', value: 'Electronic Control Systems' },
    { key: '57', value: 'Computer Hardware' },
    { key: '58', value: 'Technical Support' },
    { key: '59', value: 'System Administration' },
    { key: '60', value: 'Computer Networking' },
    { key: '61', value: 'Development Tools' },
    { key: '62', value: 'Web Development' },
    { key: '63', value: 'Data Storage Technologies' },
    { key: '64', value: 'Data Science' },
    { key: '65', value: 'Software Development Life Cycle (SDLC)' },
    { key: '66', value: 'Mobile Application Development' },
    { key: '67', value: 'Management Consulting' },
    { key: '68', value: 'Telecommunications' },
    { key: '69', value: 'Cybersecurity' },
    { key: '70', value: 'Sales Operations' },
    { key: '71', value: 'Social Media' },
    { key: '72', value: 'Digital Marketing' },
    { key: '73', value: 'Video' },
    { key: '74', value: 'Television' },
    { key: '75', value: 'Photography' },
    { key: '76', value: 'Editing' },
    { key: '77', value: 'Animation' },
    { key: '78', value: 'Theatre' },
    { key: '79', value: 'Journalism' },
    { key: '80', value: 'Radio Production' },
    { key: '81', value: 'Corporate Communications' },
    { key: '82', value: 'Literature' },
    { key: '83', value: 'Teaching' },
    { key: '84', value: 'Game Development' },
    { key: '85', value: 'Human Computer Interaction' },
    { key: '86', value: 'Information Management' },
    { key: '87', value: 'Commercial Banking' },
    { key: '88', value: 'Financial Accounting' },
    { key: '89', value: 'Capital Markets' },
    { key: '90', value: 'Investment Banking' },
    { key: '91', value: 'Insurance' },
    { key: '92', value: 'Auditing' },
    { key: '93', value: 'Growth Strategies' },
    { key: '94', value: 'Investor Relations' },
    { key: '95', value: 'Law' },
    { key: '96', value: 'Contract Law' },
    { key: '97', value: 'Labor and Employment Law' },
    { key: '98', value: 'Intellectual Property' },
    { key: '99', value: 'Family Law' },
    { key: '100', value: 'International Law' },
    { key: '101', value: 'Criminal Law' },
    { key: '102', value: 'Tax Law' },
    { key: '103', value: 'Employee Learning & Development' },
    { key: '104', value: 'Genetic Engineering' },
    { key: '105', value: 'Evolutionary Biology' },
    { key: '106', value: 'Physiology' },
    { key: '107', value: 'Organic Chemistry' },
    { key: '108', value: 'Veterinary Medicine' },
    { key: '109', value: 'Zoology' },
    { key: '110', value: 'Agricultural Production' },
    { key: '111', value: 'General Surgery' },
    { key: '112', value: 'Anesthesiology' },
    { key: '113', value: 'Tax Accounting' },
    { key: '114', value: 'Bookkeeping' },
    { key: '115', value: 'Management Accounting' },
    { key: '116', value: 'Accounts Payable' },
    { key: '117', value: 'Payroll Services' },
    { key: '118', value: 'Urban Planning' },
    { key: '119', value: 'Interior Design' },
    { key: '120', value: 'Industrial Design' },
    { key: '121', value: 'Public Policy' },
    { key: '122', value: 'Administrative Assistance' },
    { key: '123', value: 'Event Planning' },
    { key: '124', value: 'Water Engineering' },
    { key: '125', value: 'Environmental Engineering' },
    { key: '126', value: 'Competitive Strategies' },
    { key: '127', value: 'Personal Coaching' },
    { key: '128', value: 'Human Resources (HR)' },
    { key: '129', value: 'Translation' },
    { key: '130', value: 'Linguistics' },
    { key: '131', value: 'Foreign Languages' },
    { key: '132', value: 'Higher Education' },
    { key: '133', value: 'Commercial Photography' },
    { key: '134', value: 'Music' },
    { key: '135', value: 'Recreation' },
    { key: '136', value: 'Professional Sports' },
    { key: '137', value: 'Sports Coaching' },
    { key: '138', value: 'Art History' },
    { key: '139', value: 'History' },
    { key: '140', value: 'Visual Arts' },
    { key: '141', value: 'Anthropology' },
    { key: '142', value: 'Conceptual Art' },
    { key: '143', value: 'Dance' },
    { key: '144', value: 'Arts & Crafts' },
    { key: '145', value: 'Wellness' },
    { key: '146', value: 'Medicine' },
    { key: '147', value: 'Healthcare Management' },
    { key: '148', value: 'Public Health' },
    { key: '149', value: 'Physical Medicine and Rehabilitation' },
    { key: '150', value: 'Computer Graphics' },
    { key: '151', value: 'Enterprise Software' },
    { key: '152', value: 'Artificial Intelligence (AI)' },
    { key: '153', value: 'Nanotechnology' },
    { key: '154', value: 'Landscape Architecture' },
    { key: '155', value: 'Cooking' },
    { key: '156', value: 'Real Estate' },
    { key: '157', value: 'Property Law' },
    { key: '158', value: 'Customer Service Systems' }
];

export const soft = [
    { key: '1', value: 'Negotiation' },
    { key: '2', value: 'Teamwork' },
    { key: '3', value: 'Leadership' },
    { key: '4', value: 'Communication' },
    { key: '5', value: 'Writing' },
    { key: '6', value: 'Time Management' }
];

export const  proficiencyOptions = [
    { key: '1', value: 'Elementary proficiency' },
    { key: '2', value: 'Limited working proficiency' },
    { key: '3', value: 'Professional working proficiency' },
    { key: '4', value: 'Full professional proficiency' },
    { key: '5', value: 'Native or bilingual proficiency' }
];